version: '3'

services:

   app1:
     container_name: app1
     image: lwieske/java-8:server-jre-8u121-slim
     volumes:
       - ./mvc-app.war:/app/mvc-app.war
#       - ../build-artifacts/spring-boot/target/mvc-app.war:/app/mvc-app.war
       - ./app_log:/app/log/
#     ports:
#       - "18080:8080"
     command: ["java", "-jar", "/app/mvc-app.war", "&>>", "/app/log/csd-console.log &"]

   app2:
     container_name: app2
     image: lwieske/java-8:server-jre-8u121-slim
     volumes:
       - ./mvc-app.war:/app/mvc-app.war
#       - ../build-artifacts/spring-boot/target/mvc-app.war:/app/mvc-app.war
       - ./app_log:/app/log/
#     ports:
#       - "28080:8080"
     command: ["java", "-jar", "/app/mvc-app.war", "&>>", "/app/log/csd-console.log &"]

   bal:
     container_name: bal
     image: nginx:1.10.3
     depends_on:
      - app1
      - app2
     volumes:
       - ./nginx/my.conf:/etc/nginx/nginx.conf
     ports:
       - "80:80"

